### ISSUE TITLE
request for releasing on indigo

### ISSUE THREAD

**Issue by k-okada** [PR2/pr2_mechanism_msgs#1]

**Comment by UltronDestroyer** [comment]
Does the code work? I haven't installed Trusty yet.. If it does, I can bloom release it for you.

**Comment by k-okada** [comment]
yes, I have confirmed pr2 gazbeo worked on indigo with minor fix on urdf. see https://github.com/PR2/pr2_common/pull/233,

**Comment by furushchev** [comment]
This package is already released on indigo / jade. I think now it's ok to close.
